version: "3.9"
services:
  hexo-blog:
    build:
      context: .
      args:
        NODE_VERSION: 14
    container_name: hexo-blog
    image: hexo-blog:latest
    restart: always
    environment:
      HEXO_SERVER_PORT: 4080
    ports:
      - '8080:4080'
    volumes:
      - ./data/blog:/root/blog